//4326 = geo WGS84
IMPORT_ASCII FILENAME="reco.csv" SKIP_COLUMNS=9 TYPE=POINT_ONLY COORD_FORMAT=DECIMAL COORD_DELIM=AUTO COORD_ORDER=Y_FIRST INC_ELEV_COORDS=NO INC_COORD_LINE_ATTRS=YES COL_HEADERS=YES PROJ="EPSG:4326"

//utilisation d'une formule pour le même résultat : 
CALC_ATTR_FORMULA FILENAME="reco.csv" NEW_ATTR="ID" FORMULA="MCC+'.'+MNC+'.'+LAC+'.'+CI"

//SPLIT
SPLIT_LAYER FILENAME="reco.csv" SPLIT_BY_ATTR="ID"


GENERATE_LAYER_BOUNDS BOUNDS_TYPE=POLYGON

//SPLIT
SPLIT_LAYER FILENAME="Layer Bounds" SPLIT_BY_ATTR="DESCRIPTION"

