
DIR_LOOP_START DIRECTORY="%SCRIPT_FOLDER%\ConvertIn" FILENAME_MASKS="*.*" RECURSE_DIR=NO

IMPORT FILENAME="%SCRIPT_FOLDER%\ConvertIn\%FNAME%"

//4326 : GEO/WGS84
LOAD_PROJECTION PROJ="EPSG:4326"

EXPORT_RASTER FILENAME="%SCRIPT_FOLDER%\ConvertOut\%FNAME%" TYPE=GEOTIFF PALETTE=OPTIMIZED

UNLOAD_ALL
DIR_LOOP_END